### ISSUE TITLE
Add "rollup-plugin-typescript2" dependency

### ISSUE THREAD

**Issue by olegdovger** [geocine/custom-elements-ts#37]
```
➜  custom-elements-ts git:(master) ✗ yarn start counter
yarn run v1.12.3
$ node tools/start.js counter
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'rollup-plugin-typescript2'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/oleg/projects/experiments/custom-elements-ts/tools/rollup-config.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
error Command failed with exit code 1.
```

**Comment by geocine** [comment]
@olegdovger thanks for reporting, I tried to reproduce the issue using `npm` and it works due to the `package-lock.json` having the `rollup-plugin-typescript2` in it. I then tried yarn and this issue exist, will fix and get back to you.
